all:
	#g++ -pthread -shared -L/home/hac210/anaconda2/lib -Wl,-rpath=/home/hac210/anaconda2/lib,--no-as-needed build/temp.linux-x86_64-2.7/ma57_pyWrap.o build/temp.linux-x86_64-2.7/ma57_solver.o -L/usr/local/lib -L/home/hac210/anaconda2/lib -Wl,-R/usr/local/lib -lmetis -lma57 -llapack -lpython2.7 -l blas -l lapack -l gfortran -l metis -l ma57 -L /usr/local/lib -l metis -l nlopt -l arpack -L /usr/local/lib -L /usr/local/gfortran/lib -o ma57_pyWrap.so

	g++ -pthread -shared -L/home/hac210/anaconda2/lib -Wl,-rpath=/home/hac210/anaconda2/lib,--no-as-needed build/temp.linux-x86_64-2.7/ma57_pyWrap.o build/temp.linux-x86_64-2.7/ma57_solver.o -L/usr/local/lib -L/home/hac210/anaconda2/lib -Wl,-R/usr/local/lib -l blas -l lapack -l gfortran -l metis -l ma57 -L /usr/local/lib -l metis -l arpack -L /usr/local/lib -L /usr/local/gfortran/lib -lpython2.7 -o ma57_pyWrap.so



