all:
	g++ -std=c++14 -fopenmp -w -g  main.cpp -I /home/hac210/Dropbox/packages/01.M2DO_code/M2DO_LSM/include -I /home/hac210/Dropbox/packages/01.M2DO_code/M2DO_FEA/include/ -I /home/hac210/Dropbox/packages/01.M2DO_code/Vendor/eigen3 -l blas -l lapack -l gfortran -l metis -l ma57 -L /usr/local/lib -l metis -l nlopt -l arpack -L /usr/local/lib -L /usr/local/gfortran/lib 

clean:
	rm a.out
